stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"
  stage: build
  image: cmake:latest
  script:
      - cmake . -B build -DCMAKE_INSTALL_PREFIX=./build/install
      - cmake --build build
  artifacts:
      paths:
        - build/

unit-test-job:   # This job runs in the test stage.
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: cmake:latest
  script:
      - ctest --test-dir build -j
