name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: release-${{ matrix.os }}-${{ matrix.arch }}
    permissions:
      contents: write
    runs-on: ${{ matrix.runner }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      RELEASE_FILENAME: ${{ github.event.repository.name }}_release_${{ env.RELEASE_TAG }}_${{ matrix.os }}_${{ matrix.arch }}.zip
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: linux
            arch: x86_64
            runner: ubuntu-slim
            cc: gcc
            cxx: g++

          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            cc: gcc
            cxx: g++

          - os: macos
            arch: arm64
            runner: macos-latest
            cc: clang
            cxx: clang++

          - os: windows
            arch: x86_64
            runner: windows-latest
            cc: cl
            cxx: cl

          - os: windows
            arch: arm64
            runner: windows-11-arm
            cc: cl
            cxx: cl

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows' }}
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tools]
            cmake = "latest"
            ninja = "latest"
      - name: configure
        if: ${{ matrix.os != 'macos' }}
        run: cmake . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=./build/install
      - name: configure
        if: ${{ matrix.os == 'macos' }}
        run: cmake . -B build -G Ninja -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64" -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=./build/install
      - name: build
        run: cmake --build build -- install
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: ${{ env.RELEASE_FILENAME }}
          directory: build/install

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          files: build/install/${{ env.RELEASE_FILENAME }}
          draft: false
          prerelease: false

