name: test
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: test-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: linux
            arch: x86_64
            runner: ubuntu-slim
            cc: gcc
            cxx: g++

          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            cc: gcc
            cxx: g++

          - os: macos
            arch: arm64
            runner: macos-latest
            cc: clang
            cxx: clang++

          - os: windows
            arch: x86_64
            runner: windows-latest
            cc: cl
            cxx: cl

          - os: windows
            arch: arm64
            runner: windows-11-arm
            cc: cl
            cxx: cl

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows' }}
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tools]
            cmake = "latest"
            ninja = "latest"
      - name: configure
        if: ${{ matrix.os != 'macos' }}
        run: cmake . -B build -G Ninja -D BUILD_TESTING=ON
      - name: configure
        if: ${{ matrix.os == 'macos' }}
        run: cmake . -B build -G Ninja -D BUILD_TESTING=ON -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      - name: build
        run: cmake --build build
      - name: testing
        run: ctest --test-dir build -j

